### ISSUE TITLE
Error on Moodle 4.2 & 4.3

### ISSUE THREAD

**Issue by izendegi** [juacas/moodle-format_redirected#2]
Hi Juan Pablo,

I know that the plugin supports Moodle 4.0 & 4.1, but we've also tested it on Moodle 4.2 and 4.3 and when changing one course's format to this one and saving changes we get this error:

Unknown method called against format_redirected_renderer :: bulk_editing_button
    line 549 of /lib/outputrenderers.php: coding_exception thrown
    line 284 of /course/view.php: call to plugin_renderer_base->__call()

They seem related to the [bulk course activity editing functionality added on Moodle 4.2](https://moodledev.io/general/releases/4.2), so it may need some changes to make it compatible with 4.2+

**Comment by juacas** [comment]
Fixed in release v0.0.7  Commit 4567f69
Thanks for reporting.

**Comment by izendegi** [comment]
Thank you for the fast response and fix!
