### ISSUE TITLE
Format doesnt't apear in "Course formats" admin

### ISSUE THREAD

**Issue by nuria2c** [juacas/moodle-format_redirected#5]
After install the plugin, it doesn't appear in the "course foramts" in the plugin admin section. You have to go to "Plugins > Plugins overview" to find it and chanhe the parameteres.

![formats](https://github.com/juacas/moodle-format_redirected/assets/5544480/51ebfc51-0493-4d02-b57c-aa378dbcc510)
![image](https://github.com/juacas/moodle-format_redirected/assets/5544480/90f28520-9a70-427c-9d7e-2cbd995a7ef1)

**Comment by juacas** [comment]
Your screenshot shows that you disabled the plugin... Try enabling it again.

Nevertheless, the listing of plugins in admin settings is managed by moodle.
